"use strict"

const Alexa = require('alexa-sdk');

const wordsmithAPIKey = '3861c2becc354261579e06cae7bbbc775dc1c08db5b039c4a514831375823189';
const wordsmith = require('wordsmith-node-sdk')(wordsmithAPIKey, 'GreatCall'); // Make a unique user agent for your app

var handlers = {

    'GetCurrentStatusIntent': function(){
       executeIntent('GetCurrentStatusIntent');
    },
    
    'GetLocationDetailsIntent': function(){
        executeIntent('GetLocationDetailsIntent');
    },
    
    'GetActivityDetailsIntent': function(){
        executeIntent('GetActivityDetailsIntent');
    },

    'SpecifyPersonIntent': function(){
        var self = this;

        const personSlot = this.event.request.intent.slots.Person;
        let personName;
        if(personSlot && personSlot.value){
            personName = personSlot.value;
            this.attributes['personName'] = personName;
        }
        else{
            this.emit(':ask', 'Who are you talking about');
            return;
        }

        const previousIntent = this.attributes['previousIntent'];
        if(!previousIntent){
            this.emit(':ask', 'what do you want to know?');
        }
        else{
            this.emit(previousIntent);
        }

        
    }
};

function executeIntent(intentName) {
        const personSlot = this.event.request.intent.slots.Person;
        
        let personName;
        const templateName = null;  // TODO lookup in dictionary
        this.attributes['previousIntent'] = intentName;
        if(personSlot && personSlot.value){
            personName = personSlot.value;
            this.attributes['personName'] = personName;
        }
        else{
            personName = this.attributes['personName'] || null;
        }

        if(personName) {
            var data = null;  // TODO: look up in dictionary
            console.log(`Slot name ${personName}`);
            wordsmith.projects.find('wshack')
            .then(project => project.templates.find(templateName))
            .then(template => template.generate(
                   data
            ))
            .then((content) => {
            // content is the text generated by Wordsmith
            self.emit(':tell', content);
            })
            .catch((error) => {
            console.error(error);
            });
        }
        else{
            this.emit(':ask', 'Who are you talking about');
        }
}



exports.handler = function(event, context, callback) {
    var alexa = Alexa.handler(event, context);
    alexa.registerHandlers(handlers);
    alexa.execute();
};
