"use strict"

const Alexa = require('alexa-sdk');

const wordsmithAPIKey = '3861c2becc354261579e06cae7bbbc775dc1c08db5b039c4a514831375823189';
const wordsmith = require('wordsmith-node-sdk')(wordsmithAPIKey, 'GreatCall'); // Make a unique user agent for your app

var handlers = {

    'GetCurrentStatusIntent': function(){
        var self = this;

        const personSlot = this.event.request.intent.slots.Person;
        let personName;
        this.attributes['previousIntent'] = 'GetCurrentStatusIntent';
        if(personSlot && personSlot.value){
            personName = personSlot.value;
            this.attributes['personName'] = personName;
        }
        else{
            personName = this.attributes['personName'] || null;
        }

        if(personName) {
            console.log(`Slot name ${personName}`);
            wordsmith.projects.find('lively-narrative')
            .then(project => project.templates.find('lively-narrative-v1'))
            .then(template => template.generate(
                    {
                    "userid": 1,
                    "name": "Shelley High",
                    "alias": personName,
                    "gender": "Female",
                    "relationship": "Mom",
                    "steps": 4534,
                    "challengescompleted": 2,
                    "pointsearned": 8546,
                    "lastknownlocation": "Home",
                    "lastknownlocationtimestamp": 12
                    }
            ))
            .then((content) => {
            // content is the text generated by Wordsmith
            self.emit(':tell', content);
            })
            .catch((error) => {
            console.error(error);
            });
        }
        else{
            this.emit(':ask', 'Who are you talking about');
        }
        
    },

    'SpecifyPersonIntent': function(){
        var self = this;

        const personSlot = this.event.request.intent.slots.Person;
        let personName;
        if(personSlot && personSlot.value){
            personName = personSlot.value;
            this.attributes['personName'] = personName;
        }
        else{
            this.emit(':ask', 'Who are you talking about');
            return;
        }

        const previousIntent = this.attributes['previousIntent'];
        if(!previousIntent){
            this.emit(':ask', 'what do you want to know?');
        }
        else{
            this.emit(previousIntent);
        }

        
    }
};

exports.handler = function(event, context, callback) {
    var alexa = Alexa.handler(event, context);
    alexa.registerHandlers(handlers);
    alexa.execute();
};
